In [1]:
import pandas as pd
import numpy as np

In [4]:
customer = pd.read_excel(r"C:\Users\THIS\Downloads\Ecomm (2).xlsx" , sheet_name="CustomerDetail")

In [5]:
customer.shape

(24, 12)

In [6]:
orders = pd.read_excel(r"C:\Users\THIS\Downloads\Ecomm (2).xlsx", sheet_name="Jan")

In [7]:
orders.shape

(1952, 8)

In [8]:
customer.head(2)

,CustomerID,CustomerID.1,Order Date,Month,MonthName,DateInText,Customer Name,State or Province,City,Gender,Gender.1,Gender.2
0,CUS7253,7253,2015-01-07,1,Jan,01/07/2015,Bonnie Potter,Washington,Anacortes,M,1,MALE
1,CUS4875,4875,2015-06-13,6,Jun,06/13/2015,Ronnie Proctor,California,San Gabriel,F,0,FEMALE

In [9]:
orders.head(2)

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card

In [10]:
customer.columns

Index(['CustomerID', 'CustomerID.1', 'Order Date', 'Month', 'MonthName',
       'DateInText', 'Customer Name', 'State or Province', 'City', 'Gender',
       'Gender.1', 'Gender.2'],
      dtype='object')

In [11]:
customer = customer.drop(columns=['CustomerID','Month', 'MonthName','DateInText','Gender','Gender.1'])

In [12]:
customer.shape

(24, 6)

In [14]:
customer.head(3)

,CustomerID.1,Order Date,Customer Name,State or Province,City,Gender.2
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE
2,2748,2015-02-15,Marcus Dunlap,New Jersey,Roselle,MALE

In [16]:
customer = customer.rename(columns={'CustomerID.1':'CustomerID','Gender.2':'Gender'})

In [17]:
customer.head(2)

,CustomerID,Order Date,Customer Name,State or Province,City,Gender
0,7253,2015-01-07,Bonnie Potter,Washington,Anacortes,MALE
1,4875,2015-06-13,Ronnie Proctor,California,San Gabriel,FEMALE

In [18]:
orders.head(2)

,Order ID,CustomerID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,88522,4666,11.36,4.5600,4,Office Supplies,Pens & Art Supplies,Credit Card
1,90193,4663,6011.76,4390.3665,12,Furniture,Chairs & Chairmats,Credit Card

In [19]:
customer.isnull().sum()

CustomerID           0
Order Date           0
Customer Name        0
State or Province    0
City                 0
Gender               0
dtype: int64

In [20]:
orders.isnull().sum()

Order ID                0
CustomerID              0
Amount                  0
Profit                  0
Quantity ordered new    0
Product Category        0
Product Sub-Category    0
Payment Mode            0
dtype: int64

In [22]:
orders.Profit.sum()

np.float64(224114.64183714997)

In [23]:
orders.groupby('Product Category').agg({'Profit':'sum'}).reset_index()

  Product Category        Profit
0        Furniture  59249.445936
1  Office Supplies  89562.039537
2       Technology  75303.156364

In [24]:
customer.shape

(24, 6)

In [25]:
orders.shape

(1952, 8)

In [33]:
df = pd.merge(customer,orders , on="CustomerID")

In [34]:
df.shape

(1952, 13)

In [35]:
df.head(2)

,CustomerID,Order Date,Customer Name,State or Province,City,Gender,Order ID,Amount,Profit,Quantity ordered new,Product Category,Product Sub-Category,Payment Mode
0,4666,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE,88522,11.36,4.560,4,Office Supplies,Pens & Art Supplies,Credit Card
1,4666,2015-05-12,Gwendolyn F Tyson,Minnesota,Prior Lake,MALE,90669,94.27,105.678,11,Office Supplies,"Scissors, Rulers and Trimmers",Credit Card

In [38]:
df.groupby('State or Province').agg({'Profit':'sum'}).reset_index()

  State or Province        Profit
0        California  31886.448316
1         Minnesota  34330.365504
2           Montana  15291.345669
3          New York  98143.568974
4            Oregon  44462.913374

In [40]:
df.groupby('Gender').agg({'Profit':'sum'}).reset_index()

   Gender         Profit
0  FEMALE   67504.015857
1    MALE  156610.625980

In [41]:
df.Gender.value_counts()

Gender
MALE      1405
FEMALE     547
Name: count, dtype: int64