In [1]:
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

In [2]:
df = sns.load_dataset("tips")

In [3]:
df.shape

(244, 7)

In [5]:
df.head(2)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3

In [6]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [7]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [8]:
df.sex.unique()

['Female', 'Male']
Categories (2, object): ['Male', 'Female']

In [9]:
df.smoker.unique()

['No', 'Yes']
Categories (2, object): ['Yes', 'No']

In [11]:
df.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [12]:
df.time.unique()

['Dinner', 'Lunch']
Categories (2, object): ['Lunch', 'Dinner']

In [15]:
X = df[["total_bill", "size", "sex", "smoker", "day", "time" ]]

In [16]:

X.sex = X.sex.map(lambda x: 1 if x == 'Male' else 0 )
X.smoker = X.smoker.map(lambda x: 1 if x == 'Yes' else 0 )
X.day = X.day.map(lambda x: list(X.day.unique()).index(x))
X.time = X.time.map(lambda x: 0 if x == 'Lunch' else 1)

C:\Users\THIS\AppData\Local\Temp\ipykernel_9172\1247566965.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.sex = X.sex.map(lambda x: 1 if x == 'Male' else 0 )
C:\Users\THIS\AppData\Local\Temp\ipykernel_9172\1247566965.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.smoker = X.smoker.map(lambda x: 1 if x == 'Yes' else 0 )
C:\Users\THIS\AppData\Local\Temp\ipykernel_9172\1247566965.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.day = X.day.map(lambda x: list(X.day.unique()).index(x))
C:\Users\THIS\AppData\Local\Temp\ipykernel_9172\1247566965.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X.time = X.time.map(lambda x: 0 if x == 'Lunch' else 1)

In [17]:
X

     total_bill  size sex smoker day time
0         16.99     2   0      0   0    1
1         10.34     3   1      0   0    1
2         21.01     3   1      0   0    1
3         23.68     2   1      0   0    1
4         24.59     4   0      0   0    1
..          ...   ...  ..    ...  ..  ...
239       29.03     3   1      0   1    1
240       27.18     2   0      1   1    1
241       22.67     2   1      1   1    1
242       17.82     2   1      0   1    1
243       18.78     2   0      0   2    1

[244 rows x 6 columns]