In [1]:
# Web Scraping

In [3]:
import requests

In [2]:
url = "https://github.com/topics"

In [4]:
content = requests.get(url)

In [5]:
content

In [7]:
content.text[:500]

'\n\n<!DOCTYPE html>\n<html\n  lang="en"\n  \n  data-color-mode="auto" data-light-theme="light" data-dark-theme="dark"\n  data-a11y-animated-images="system" data-a11y-link-underlines="true"\n  \n  >\n\n\n\n\n  <head>\n    <meta charset="utf-8">\n  <link rel="dns-prefetch" href="https://github.githubassets.com">\n  <link rel="dns-prefetch" href="https://avatars.githubusercontent.com">\n  <link rel="dns-prefetch" href="https://github-cloud.s3.amazonaws.com">\n  <link rel="dns-prefetch" href="https://user-images.githu'

In [8]:
!pip install BeautifulSoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: BeautifulSoup4 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (4.13.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from BeautifulSoup4) (2.7)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\croma campus\appdata\roaming\python\python313\site-packages (from BeautifulSoup4) (4.14.1)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
from bs4 import BeautifulSoup

In [11]:
soup = BeautifulSoup(content.text , "html.parser")

In [13]:
len(soup)

5

In [14]:
soup.find('a',class_='no-underline flex-1 d-flex flex-column')

<a class="no-underline flex-1 d-flex flex-column" href="/topics/awesome">
<p class="f3 lh-condensed mb-0 mt-1 Link--primary">Awesome Lists</p>
<p class="f5 color-fg-muted mb-0 mt-1">
          An awesome list is a list of awesome things curated by the community.
        </p>
</a>

In [43]:
topics = []
desc = []
link = []

In [44]:
for row in soup.find_all('a',class_='no-underline flex-1 d-flex flex-column'):
    topics.append(row.find('p').text.strip())
    desc.append(row.find_all('p')[1].text.strip())
    link.append("https://github.com"+row['href'])

In [45]:
data = {
    'Topic_Names':topics,
    'Link':link,
    'Description':desc
}

In [46]:
import pandas as pd

In [47]:
df = pd.DataFrame(data)

In [48]:
df.shape

(16, 3)

In [49]:
df.head(2)

,Topic_Names,Link,Description
0,Awesome Lists,https://github.com/topics/awesome,An awesome list is a list of awesome things cu...
1,Chrome,https://github.com/topics/chrome,Chrome is a web browser from the tech company ...

In [51]:
df['Link'][0]

'https://github.com/topics/awesome'

In [75]:
users = []
repo = []
link = []
star = []

In [76]:
for url in df['Link']:
    content = requests.get(url)
    soup = BeautifulSoup(content.text , 'html.parser')
    for row in soup.find_all('div',class_='d-flex flex-justify-between flex-items-start flex-wrap gap-2 tmp-my-3'):
        users.append(row.find('a').text.strip())
        repo.append(row.find_all('a')[1].text.strip())
        link.append('https://github.com'+row.find_all('a')[1]['href'].strip())
        star.append(row.find('span',id="repo-stars-counter-star")['title'].strip())

In [77]:
data = {
    'Username':users,
    'Repository':repo,
    'Rating':star,
    'Link':link
}

In [78]:
df = pd.DataFrame(data)

In [79]:
df.shape

(320, 4)

In [80]:
df.head()

,Username,Repository,Rating,Link
0,sindresorhus,awesome,"445,336",https://github.com/sindresorhus/awesome
1,vinta,awesome-python,"287,037",https://github.com/vinta/awesome-python
2,awesome-selfhosted,awesome-selfhosted,"279,816",https://github.com/awesome-selfhosted/awesome-...
3,trimstray,the-book-of-secret-knowledge,"209,940",https://github.com/trimstray/the-book-of-secre...
4,avelino,awesome-go,"167,303",https://github.com/avelino/awesome-go

In [81]:
# HW :   https://boxofficemojo.com