### Association Rules in Machine Learning

In [1]:
# Bread , Milk , Jam
# Bread , Milk , Butter
# Bread , Butter
# Milk , Butter
# Bread , Jam , Milk
# Milk , Butter , Jam , Bread

#### 1. Itemset
A collection of items purchased together<br>
Example Transactions<br>
- Bread , Milk , Jam
- Bread , Milk , Butter
- Bread , Butter
- Milk , Butter
- Bread , Jam , Milk
- Milk , Butter , Jam , Bread

#### 2- Support
support = Total no transaction (M & B) / total transaction  =>  4/6 => 0.66

#### 3- Confidence
confidence = Support(M & B)/Support(M) => 4/5 => 0.80

#### 4- Lift
- lift = 1 , No Association
- lift < 1 , Negative Association
- lift > 1 , Positive Association <br>
lift = Confidence (A->B)/Support(A&B) => 0.88/0.66 => 1.33

In [4]:
data = [
    ['Bread' , 'Milk' , 'Jam'],
    ['Bread' , 'Milk' , 'Butter'],
    ['Bread' , 'Butter'],
    ['Milk' , 'Butter'],
    ['Bread' , 'Jam' , 'Milk'],
    ['Milk' , 'Butter' , 'Jam' , 'Bread']
]

In [14]:
# !pip install mlxtend

In [6]:
import pandas as pd
from mlxtend.frequent_patterns import apriori , association_rules

In [7]:
from mlxtend.preprocessing import TransactionEncoder

In [8]:
te = TransactionEncoder()

In [9]:
te_data = te.fit(data).transform(data)

In [10]:
te_data

array([[ True, False,  True,  True],
       [ True,  True, False,  True],
       [ True,  True, False, False],
       [False,  True, False,  True],
       [ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [11]:
df = pd.DataFrame(te_data , columns=te.columns_)

In [12]:
df

   Bread  Butter    Jam   Milk
0   True   False   True   True
1   True    True  False   True
2   True    True  False  False
3  False    True  False   True
4   True   False   True   True
5   True    True   True   True

In [15]:
frequent_itemsets = apriori(df , min_support=0.4 , use_colnames = True)

In [16]:
frequent_itemsets

    support            itemsets
0  0.833333             (Bread)
1  0.666667            (Butter)
2  0.500000               (Jam)
3  0.833333              (Milk)
4  0.500000     (Bread, Butter)
5  0.500000        (Bread, Jam)
6  0.666667       (Bread, Milk)
7  0.500000      (Butter, Milk)
8  0.500000         (Jam, Milk)
9  0.500000  (Bread, Jam, Milk)

In [17]:
rules = association_rules( frequent_itemsets , metric='confidence' )

In [21]:
rules[['antecedents','consequents','support','confidence','lift']]

    antecedents    consequents  support  confidence  lift
0         (Jam)        (Bread)      0.5         1.0   1.2
1         (Jam)         (Milk)      0.5         1.0   1.2
2  (Bread, Jam)         (Milk)      0.5         1.0   1.2
3   (Jam, Milk)        (Bread)      0.5         1.0   1.2
4         (Jam)  (Bread, Milk)      0.5         1.0   1.5